# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  # Build and Push
  - name: "gcr.io/cloud-builders/docker"
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      [
        "build",
        "--build-arg",
        "PROJECT_ID=${PROJECT_ID}",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:${_COMMIT_SHA}",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:${_COMMIT_SHA}",
      ]

  # Deploy to Staging
  # Deploy to GKE
  - name: "gcr.io/cloud-builders/gcloud"
    id: get-credentials
    entrypoint: gcloud
    args:
      - "container"
      - "clusters"
      - "get-credentials"
      - "${_CLUSTER_NAME}"
      - "--region"
      - "${_CLUSTER_REGION}"
      - "--project"
      - "${PROJECT_ID}"

  - name: "gcr.io/cloud-builders/kubectl"
    id: deploy-gke
    args:
      - "apply"
      - "-f"
      - "../k8s/configmap.yaml"
      - "-f"
      - "../k8s/frontend-deployment.yaml"
      - "-f"
      - "../k8s/frontend-service.yaml"

substitutions:
  _REGION: us-central1
  _ARTIFACT_REGISTRY_REPO_NAME: building-permit
  _CONTAINER_NAME: building-permit-frontend
  _COMMIT_SHA: latest
  _API_URL: http://localhost:8080 # Default for local, should be overridden in Cloud Build trigger

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:${_COMMIT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
  requestedVerifyOption: VERIFIED
