# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  # Build and Push
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:latest || exit 0']
  - name: "gcr.io/cloud-builders/docker"
    env:
      - 'DOCKER_BUILDKIT=1'
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:${_COMMIT_SHA}",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:latest",
        "--cache-from",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:${_COMMIT_SHA}",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:latest",
      ]

  # Deploy to Staging
  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-staging
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_CONTAINER_NAME}"
      - "--project"
      - "${PROJECT_ID}"
      - "--region"
      - "${_REGION}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:${_COMMIT_SHA}"
      - "--port"
      - "8080"
      - "--cpu"
      - "2000m"
      - "--memory"
      - "8Gi"
      - "--concurrency"
      - "40"
      - "--concurrency"
      - "10"
      - "--service-account"
      - "build-permit-sa@${PROJECT_ID}.iam.gserviceaccount.com"
      - "--set-env-vars"
      - 'GOOGLE_CLOUD_LOCATION=${_REGION},GOOGLE_CLOUD_PROJECT=${PROJECT_ID},DOCUMENT_AI_LOCATION=${_DOCUMENT_AI_LOCATION},DOCUMENT_AI_PROCESSOR_ID=${_DOCUMENT_AI_PROCESSOR_ID},VERTEX_RAG_CORPUS_NAME=projects/${PROJECT_ID}/locations/us-west1/ragCorpora/{_RAG_CORPORA},REASONING_ENGINE_APP_NAME=projects/${PROJECT_ID}/locations/${_REGION}/reasoningEngines/3166398874436763648,GEMINI_MODEL_NAME=${_GEMINI_MODEL_NAME},CONTRACTOR_AGENT_URL=https://building-permit-contractor-agent-${PROJECT_NUMBER}.${_REGION}.run.app/a2a/building_permit_contractor_agent/.well-known/agent-card.json,ASSESSOR_MCP_SERVER_URL=https://building-permit-assessor-mcp-${PROJECT_NUMBER}.${_REGION}.run.app/mcp,BQ_ANALYTICS_GCS_BUCKET=${PROJECT_ID},BQ_ANALYTICS_CONNECTION_ID=${PROJECT_ID}'
      - "--startup-probe"
      - 'initialDelaySeconds=30,tcpSocket.port=8080,timeoutSeconds=240,periodSeconds=240,failureThreshold=1'
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "1"
      - "--min=1"
      - "--max=1"
      - "--allow-unauthenticated"
      - "--timeout"
      - "300"
      - "--cpu-boost"
      - "--session-affinity"
      - "--ingress"
      - "all"
      - "--labels=appid=building-permit"

substitutions:
  _REGION: ${_REGION}
  _ARTIFACT_REGISTRY_REPO_NAME: building-permit
  _CONTAINER_NAME: building-permit-agent
  _COMMIT_SHA: ${_COMMIT_SHA}
  _DOCUMENT_AI_LOCATION: us
  _DOCUMENT_AI_PROCESSOR_ID: 24ec41d66617b372
  _RAG_CORPORA: 4611686018427387904
  _GEMINI_MODEL_NAME: gemini-2.5-pro

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:${_COMMIT_SHA}
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME:latest

options:
  pool:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
  requestedVerifyOption: VERIFIED
